:toc: macro
:toclevels: 4
:toc-title:
:toc-placement!:
:source-highlighter:

= TL;DR

_To boot the CHERI-BGAS system, run the following commands assuming all tools are installed, disk images and filenames match, etc..._

_Read the later sections for more details_

=== Prepare the RISCV FPGA soft-core and bring up FreeBSD on the DE10Pro's ARM HPS system

```sh
# host machine
quartus_pgm -m jtag -o P\;cheri-bgas-socfpga-25012022-12_02.hps.rbf@2 && picocom -b 115200 /dev/ttyUSB0
# DE10Pro's ARM HPS ...
# u-boot
fatload mmc 0:1 1000 cheri-bgas-socfpga-25012022-12_02.core.rbf
fpga load 0 1000 ${filesize}
bridge enable
fatload mmc 0:1 0x2000000 efi/boot/bootaa64.efi
fatload mmc 0:1 0x8000000 socfpga_stratix10_de10_pro2.dtb
bootefi 0x2000000 0x8000000
# FreeBSD loader
load disk0s1:de10-kernel-fmem
set currdev=disk0s2:
include /boot/lua/loader.lua
# FreeBSD prompt...
```

=== Boot FreeBSD on the RISCV soft-core

==== first terminal: RISCV gdb stub
```sh
# ARM HPS FreeBSD prompt
setenv RISCV_GDB_STUB_FMEM_DEV /dev/fmem_sys0_debug_unit
setenv RISCV_GDB_STUB_PORT 81
RISCV_gdbstub/src/main
```

==== second terminal: run `cu` to connect to the RISCV soft-core uart
```sh
# ARM HPS FreeBSD prompt
cu -l /dev/ttyu0
# enter when the gdb commands are sent in the third terminal

# ... RISCV FreeBSD prompt

```

==== third terminal: gdb session to drive the RISCV soft-core
```gdb
# ARM HPS FreeBSD prompt
cd /root/riscv-freebsd-boot
gdb bbl-riscv64
# gdb prompt
target remote localhost:81
load devicetree.wrapped.elf
load kernel-riscv64.GFE-NODEBUG
load
set $a0 = 0
set $a1 = 0x80000000
continue
# see output of second terminal
```

[discrete]
= Contents

toc::[]

:sectnums:

= Prepare the SD card

The first step to booting a software ecosystem on the DE10Pro CHERI-BGAS setup
is to prepare an  SD card with a FAT partition for boot, and a FreeBSD rootfs
partition to be used by the FreeBSD instance that will run on the ARM HPS system.

One can do so using https://github.com/CTSRD-CHERI/cheribuild.git[cheribuild]
by running:
```sh
./cheribuild.py --source-root=<path to your cheri build source root, a.k.a. /home/gameboo/devstuff/cheri> --freebsd/repository=https://github.com/CTSRD-CHERI/freebsd-morello --freebsd/git-revision=stratix10 --freebsd/toolchain=system-llvm freebsd-aarch64 disk-image-freebsd-aarch64
```

Extra files can be added to the final FreeBSD rootfs by placing them in
`<path to your cheri build source root, a.k.a. /home/gameboo/devstuff/cheri>/extra-files/\*`
**prior to running the command**. Here, we will want to add a `*.dtbo` device tree
overlay describing the FPGA hardware exposed to the HPS ARM system (RISCV debug unit, uart, interrupts...)
and a `/boot/loader.conf.local` configuration file to point to it, to enable the FreeBSD running on the ARM
HPS to interface with this hardware.

== Fat partition

- a u-boot binary
- the `*.core.rbf` to use for the fpga configuration
- the `*.dtb` for the ARM HPS system
- the `*.efi` bsd loader
- the (fmem-enabled, with this driver:
  https://github.com/CTSRD-CHERI/freebsd-morello/blob/stratix10/sys/arm64/intel/fmem.c)
  FreeBSD kernel to boot

=== Embed a bootloader and get an hps and a core slice from a bitfile

(TODO, find another source for u-boot...updt: use https://raw.githubusercontent.com/POETSII/DE10Pro-hps-ubuntu-sdcard-scripts/0f671c7726ab2b65011ed5632b7eb2d96cef9c80/build_uboot.sh)

You can build u-boot following the instructions at
https://github.com/POETSII/DE10Pro-getting-started.git (which uses
https://github.com/POETSII/DE10Pro-hps-ubuntu-sdcard.git).
You can then embed the u-boot binary in your startix 10 `\*.sof` file and split
it into a `*.hps.rbf` and a `*.core.rbf` with the following commands:

```sh
BOOTLOADER=<path to DE10Pro-hps-ubuntu-sdcard>/u-boot-socfpga/spl/u-boot-spl-dtb.ihex
SOF=<path to your stratix 10 *.sof file>
OUTNAME=socfpga
quartus_cpf --bootloader=$BOOTLOADER $SOF $OUTNAME.sof
quartus_cpf -c --hps -o bitstream_compression=on $OUTNAME.sof $OUTNAME.rbf
# or possibly:
# quartus_pfg -c $SOF -o hps=ON -o hps_path=$BOOTLOADER $OUTNAME.rbf
```

== FreeBSD rootfs partition

On the FreeBSD rootfs, we need:

- a FreeBSD rootfs ;)
- a loader script `/boot/lua/loader.lua` to be included from the FreeBSD loader
  when booting FreeBSD
- to make the ARM HPS system FreeBSD instance able to communicate with the
  RISCV FPGA soft-core, we need it to detect the uart on the FPGA side. To do
  this, we need:
  * a device tree overlay `/boot/fpga-ns16550.dtbo`
  * a loader configuration `/boot/loader.conf.local` containing
    `fdt_overlays="/boot/fpga-ns16550.dtbo"`
- possibly your ssh keys to help ssh-ing into the ARM HPS system
- optionally, in `/etc/rc.conf` add
```sh
ifconfig_<interface name, a.k.a. dwc0>="inet <ip for the ARM HPS system, e.g. 192.168.10.10/24>"
defaultrouter="<ip of a host machine to act as a router, e.g. 192.168.10.1>"
```
- optionally, in `/etc/resolv.conf` add
```sh
nameserver 8.8.8.8
nameserver 208.67.222.222
nameserver 208.67.220.220
```
- a clone of https://github.com/bukinr/RISCV_gdbstub.git to enable gdb sessions
  to the RISCV FPGA soft-core
- a clone of https://github.com/CTSRD-CHERI/fmem.git to interact with the
  various fmem devices from the command line
- git / vim / gcc / whatever tools...

= Prepare the RISCV FPGA soft-core system

== Push the hps rbf slice to the board and get a usb terminal going

From the host machine driving the DE10pro board:

```sh
RBF=<path to your stratix 10 *.hps.rbf file>
quartus_pgm -m jtag -o P\;$RBF@2 && picocom -b 115200 /dev/ttyUSB0
```

== Push the core rbf slice from the sdcard to the FPGA and setup the AXI bridges

From the u-boot prompt on the ARM HPS system:

```uboot
fatload mmc 0:1 1000 <FAT partition path to your stratix 10 *.core.rbf file>
fpga load 0 1000 ${filesize}
bridge enable
```

=== side note - other useful u-boot commands:

```uboot
printenv
usb start
usb info
fatload usb ...
```

= Boot FreeBSD on the ARM HPS system

== Get to the BSD loader

From the u-boot prompt on the ARM HPS system:

```uboot
fatload mmc 0:1 0x2000000 <FAT partition path to your *.efi FreeBSD loader file>
fatload mmc 0:1 0x8000000 <FAT partition path to your *.dtb device tree file>
bootefi 0x2000000 0x8000000
```

== Actually boot FreeBSD

From the FreeBSD loader prompt:

```bsdloader
load <disk0s1>:</path/to/kernel>
set currdev=<disk0s2:>
include <ROOTFS path to loader script, e.g. /boot/lua/loader.lua>
boot
```

=== side note - other useful FreeBSD loader commands:

Misc:

```bsdloader
show
fdt ls
```

To specify the usb drive as the rootfs on FreeBSD boot:

```sh
ufs:diskid/DISK-20090815198100000s2a
```

= Get a FreeBSD prompt on the RISCV FPGA soft-core system

== Get a GDB session to the RISCV FPGA soft-core

Once FreeBSD is booted on the ARM HPS system:

- Run RISCV gdb stub from an ARM HPS system FreeBSD prompt. RISCV gdb stub can
  be cloned from https://github.com/bukinr/RISCV_gdbstub.git and built simply
  using `make`.
- Once a RISCV gdb stub session is running on the ARM HPS system, connect a
  riscv gdb session. This should be done from a machine which has access to:
  * a RISCV bbl bootloader
  * a RISCV FreeBSD kernel
  * a device tree for the RISCV FPGA soft-core system (see
    https://github.com/gameboo/DE10Pro-softcore-devicetree.git)
  Typically, you would run on the same host machine driving the DE10Pro board
  `gdb-multiarch <path to RISCV bbl>` (running gdb-multiarch wih a riscv binary
  as argument will ensure a riscv-gdb session) and connect to the RISCV gdb
  stub running (on port 81) on the ARM HPS system with `target remote <DE10Pro
  board ip or hostname>:81`

== Boot the RISCV FPGA soft-core system

From the gdb session to the RISCV FPGA soft-core:

- load the RISCV system's device tree (the one generated from
  https://github.com/gameboo/DE10Pro-softcore-devicetree.git is wrapped in an
  elf container which will load at address `0x80000000`):
  `load <path to the elf container for the RISCV system's device tree>`
- load the RISCV FreeBSD kernel: `load <path to the RISCV FreeBSD kernel>`
- load the bbl bootloader: `load`
- set the `a0` and `a1` argument registers to bbl with the hart id and device
  tree address respectively:
  * `set $a0 = 0`
  * `set $a1 = <device tree load address, e.g. 0x80000000>`
- send the RISCV core running: `continue`

== Connect a prompt to the RISCV FPGA soft-core system UART

From an ARM FreeBSD prompt, connect to the uart using `cu -l /dev/ttyu0` (this
`/dev/ttyu0` device should have been detected by virtue of having booted the
ARM FreeBSD kernel with the previously mentioned device tree overlay).
